"""new fields in user model

Revision ID: 500a4a8250a9
Revises: 638b3353eae5
Create Date: 2025-05-13 15:50:55.513566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500a4a8250a9'
down_revision = '638b3353eae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
