"""new fields in user model

Revision ID: 556d4a4d4e06
Revises: f7bfe308bc3d
Create Date: 2025-05-12 17:28:39.760135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556d4a4d4e06'
down_revision = 'f7bfe308bc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
