"""followers

Revision ID: 584218e7d6ac
Revises: e8bd2a27b11c
Create Date: 2025-05-12 14:53:07.397507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584218e7d6ac'
down_revision = 'e8bd2a27b11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
