"""New User atributtes

Revision ID: 814690fc42e7
Revises: b88a23c0b5c4
Create Date: 2025-05-12 16:24:15.913665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814690fc42e7'
down_revision = 'b88a23c0b5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
